name: digimed
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1+39

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  connectivity_plus: ^6.1.4
  http: ^1.1.2
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  flutter_svg: ^2.0.10+1
  proste_bezier_curve: ^2.0.2
  intl: ^0.20.2
  image_picker: ^1.0.0
  image_cropper: ^9.0.0
  intl_phone_field: ^3.2.0
  fl_chart: ^1.1.1
  persistent_bottom_nav_bar: ^6.2.1
  lottie: ^3.0.0
  graphql_flutter: ^5.1.2
  cached_network_image: ^3.4.1
  country_dial_code: ^1.2.0
  flutter_image_compress: ^2.1.0
  flutter_localization: ^0.2.0
  geolocator: ^10.1.0
  pin_code_fields: ^8.0.1
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.2.1
  firebase_core: ^3.14.0
  shared_preferences: ^2.5.3
  local_auth: ^2.1.7
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  flutter_timezone: ^4.1.1
  logger: ^2.5.0
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  flutter_gen_runner: ^5.11.0
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.2.2
  url_launcher: ^6.2.4

dependency_overrides:
  vector_math: ^2.2.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  image_path_ios: "assets/icon/logo.png"
  adaptive_icon_background: "#10006D"
  background_color_ios: "#10006D"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/icon/
    - assets/lottiefiles/

  fonts:
    - family: DigimedIcon
      fonts:
        - asset: assets/fonts/Digimed_Icon.ttf
    - family: NotificationIcons
      fonts:
        - asset: assets/fonts/NotificationIcons.ttf
    - family: DanielDigimedIcon
      fonts:
        - asset: assets/fonts/DanielDigimedIcon.ttf
    - family: IAIcons
      fonts:
        - asset: assets/fonts/IAIcons.ttf
    - family: IATools
      fonts:
        - asset: assets/fonts/ToolsDimed.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf

flutter_gen:
  output: lib/app/generated/
  integrations:
    flutter_svg: true